# Generated by Django 5.2.4 on 2025-07-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('timestamp',)},
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_edited',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_at',
        ),
        migrations.AlterModelTable(
            name='conversation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='message',
            table=None,
        ),
        migrations.DeleteModel(
            name='MessageAttachment',
        ),
    ]
